/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab7.frontend;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.SwingUtilities.getWindowAncestor;
import lab7.*;

/**
 *
 * @author Malak Mokhtar
 */

public class AddLessonFrame extends javax.swing.JPanel {
    String title;

    /**
     * Creates new form AddLessonFrame
     */
    public AddLessonFrame(String title) {
        initComponents();
        this.title=title;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLEsson = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        titleButton = new javax.swing.JLabel();
        Co = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        titleTextField = new javax.swing.JTextField();
        contentField = new javax.swing.JTextField();
        resorcesField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        addLEsson.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addLEsson.setText("Add Lesson");

        idLabel.setText("Lesson ID:");

        titleButton.setText("Title:");

        Co.setText("Content:");

        jLabel1.setText("Resources comma separated");

        backButton.setText("Go Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(backButton)
                        .addGap(227, 227, 227)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(resorcesField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addLEsson, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idLabel)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Co)
                                                .addComponent(titleButton))))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(contentField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addLEsson)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Co)
                            .addComponent(contentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(resorcesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(jButton1))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ManageLessons m = new ManageLessons();
            java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
            
            if (window instanceof javax.swing.JFrame frame) {
                frame.setContentPane(m);
                frame.revalidate();
                frame.repaint();
            }
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 if (idField.getText().isEmpty() || titleTextField.getText().isEmpty() 
            || contentField.getText().isEmpty() ) {
        JOptionPane.showMessageDialog(this, "Error: You have to fill out all the fields");
        return;
    }
    try {
        String lessonTitle = titleTextField.getText().trim();
        int id = Integer.parseInt(idField.getText().trim());
        String content = contentField.getText().trim();
        String line = resorcesField.getText().trim();
        ArrayList<String> resources = new ArrayList<>();
        if (!line.isEmpty()) {
            String[] arr = line.split(",");
            for (String r : arr) {
                resources.add(r.trim());
            }
        }
        Lesson lesson = new Lesson(id, lessonTitle, content);
        lesson.setResources(resources);
        // Load courses safely
        ArrayList<Course> courses = JsonDatabaseManager.loadCourses();
        for (Course course : courses) {
            if (course.getTitle().equals(this.title)) {
         
                // Ensure lessons list is not null
                if (course.getLessons() == null) {
                    course.setLessons(new ArrayList<>());
                }
                course.getLessons().add(lesson);
                // Save updated courses
                JsonDatabaseManager.saveCourse(courses);
                JOptionPane.showMessageDialog(this, "Lesson saved successfully!");
                break;
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Lesson ID. It must be a number.");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving lesson. Try again later.");
        e.printStackTrace();  
}  
    }//GEN-LAST:event_jButton1ActionPerformed

                                         


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Co;
    private javax.swing.JLabel addLEsson;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField contentField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField resorcesField;
    private javax.swing.JLabel titleButton;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
