/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab7.frontend;

import java.awt.print.PrinterException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.SwingUtilities.getWindowAncestor;
import javax.swing.table.DefaultTableModel;
import lab7.*;

/**
 *
 * @author Malak Mokhtar
 */
public class CertificatePanel extends javax.swing.JPanel {

    private Student student;
    private ArrayList<Course> passedCourses;

    /**
     * Creates new form CertificatePanel
     */
    public CertificatePanel(Student student, ArrayList<Course> passedCourses) throws IOException {
        initComponents();
        this.student = student;
        this.passedCourses = passedCourses;
        loadTable(passedCourses);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        downloadBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        viewButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Student Completed Courses");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Title", "Certificate ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        downloadBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "JSON", " " }));
        downloadBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Download");

        viewButton.setText("Vew Certificate");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(47, 47, 47)
                        .addComponent(viewButton)
                        .addGap(69, 69, 69)
                        .addComponent(downloadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(downloadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFrame frame = (JFrame) getWindowAncestor(this);
        frame.setContentPane(new StudentDashboardFrame(student).getContentPane());
        frame.revalidate();
        frame.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void downloadBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadBoxActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        Certificate c=null;
        if (selectedRow == -1) {
            // No row selected
            JOptionPane.showMessageDialog(this, "Please select a course to download Certificate");
            return;
        } else {

            String download = downloadBox.getSelectedItem().toString();
            String cId = (String) model.getValueAt(selectedRow, 1);
            ArrayList<Certificate> certArr=student.getCertificates();
            for(int i =0;i<certArr.size();i++)
            {
                if(certArr.get(i).getCertificateId().equals(cId))
                     c=certArr.get(i);
                break;       
            }
            if (download.equals("PDF")) {

                PDFCertificate pdf = new PDFCertificate(c);
                try {
                    pdf.createPDF();
                } catch (IOException ex) {
                    Logger.getLogger(CertificatePanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    JsonDatabaseManager.exportCertificateAsJson(c);
                } catch (IOException ex) {
                    Logger.getLogger(CertificatePanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Certificate JSON downloaded!");
            }
        }


    }//GEN-LAST:event_downloadBoxActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        Certificate c=null;
        if (selectedRow == -1) {
           
            JOptionPane.showMessageDialog(this, "Please select a course to view Certificate");
            return;
        } else {  
            String cId = (String) model.getValueAt(selectedRow, 1);
            ArrayList<Certificate> certArr=student.getCertificates();
            for(int i =0;i<certArr.size();i++)
            {
                if(certArr.get(i).getCertificateId().equals(cId))
                {   c=certArr.get(i);
                break;
                }
            }
        ViewCertificate v = new ViewCertificate(student,passedCourses,c);
        
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof javax.swing.JFrame frame) {
            frame.setContentPane(v);
            frame.revalidate();
            frame.repaint();
        }
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    public void loadTable(ArrayList<Course> courses) throws IOException {
    DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
    m.setRowCount(0);

    for (Course c : courses) {
        Certificate existingCert = null;

        for (Certificate cert : student.getCertificates()) {
            if (cert.getCourseId()==c.getCourseID()) {
                existingCert = cert;
                break;
            }
        }
        if (existingCert == null) {
            existingCert = Certificate.generateCertificate(student, c);
            student.getCertificates().add(existingCert); // Store it in student
            c.setCertificate(existingCert);
        } else {
            c.setCertificate(existingCert);
        }
        m.addRow(new Object[]{c.getTitle(),c.getCertificate().getCertificateId()});
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> downloadBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
