/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab7.frontend;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.SwingUtilities.getWindowAncestor;
import javax.swing.table.DefaultTableModel;
import lab7.*;

/**
 *
 * @author farida helal
 */
public class MarkLessons extends javax.swing.JPanel {

    private int courseID ;
    private StudentManager sm;
    private Student s;
         
    public MarkLessons(int courseID,StudentManager sm,Student s) throws IOException {
        initComponents();
        this.sm=sm;
        this.s = s;
        this.courseID = courseID;
        loadTable(sm.lessonList(courseID));
    }

    public void loadTable(ArrayList<Lesson> lessons) {
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);

        // Get student progress for this course
        ArrayList<LessonProgress> cp = sm.getLessonProgressbyId(courseID);

        for (Lesson lesson : lessons) {
            boolean completed = sm.isComplete(courseID,lesson.getLessonId());
            model.addRow(new Object[]{
                lesson.getTitle(),
                lesson.getLessonId(),
                completed ? "Completed" : "Not Completed"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        quizButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title ", "Lesson ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Go back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        quizButton.setText("Take Quiz");
        quizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(quizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(quizButton))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ViewEnrolledCourses m = new ViewEnrolledCourses(sm,s);
            java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
            
            if (window instanceof javax.swing.JFrame frame) {
                frame.setContentPane(m);
                frame.revalidate();
                frame.repaint();
            }
        } catch (IOException ex) {
            Logger.getLogger(MarkLessons.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void quizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a lesson.");
            return;
        }
        
        int lessonId = (int) jTable1.getValueAt(selectedRow, 1);
        
        Lesson selectedLesson = null;
        try {
            for (Lesson l : sm.lessonList(courseID)) {
                if (l.getLessonId() == lessonId) {
                    selectedLesson = l;
                    break;
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error loading lesson");
            return;
        }
        
        if (selectedLesson == null) {
            JOptionPane.showConfirmDialog(this, "Lesson not found");
            return;
        }
        
        try {
            if (!sm.canAccessLesson(courseID, lessonId)) {
                JOptionPane.showMessageDialog(this, "You must complete previous lessons before taking this quiz !", "Access Denied", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error checking lesson access");
            return;
        }
        
        if (selectedLesson.getQuiz() == null || selectedLesson.getQuiz().getQuestions() == null || selectedLesson.getQuiz().getQuestions().isEmpty()) {
            JOptionPane.showMessageDialog(this, "This lesson has no quiz", "Quiz Not Found", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!sm.canAttemptQuiz(lessonId)) {
            JOptionPane.showMessageDialog(this, "You have reached the maximum number of attempts for this quiz !", "Max Attempts Reached", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        QuizPanel qp = new QuizPanel(sm, s, courseID, selectedLesson);
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        
        if (window instanceof javax.swing.JFrame frame) {
            frame.setContentPane(qp);
            frame.revalidate();
            frame.repaint();
            frame.setMinimumSize(new java.awt.Dimension(900,700));
            frame.setSize(900, 700);
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_quizButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton quizButton;
    // End of variables declaration//GEN-END:variables
}
