/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab7.frontend;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import lab7.Lesson;
import lab7.Question;
import lab7.Quiz;
import lab7.QuizAttempt;
import lab7.Student;
import lab7.StudentManager;

/**
 *
 * @author NEXT STORE
 */
public class QuizPanel extends javax.swing.JPanel {

    private StudentManager sm;
    private Student s;
    private int courseID;
    private Lesson lesson;
    private ArrayList<JLabel> questionLabels = new ArrayList<>();
    private ArrayList<ButtonGroup> optionGroups = new ArrayList<>();
    private ArrayList<JLabel> feedbackLabels = new ArrayList<>();
    private java.awt.Dimension previousSize;
    
    /**
     * Creates new form QuizPanel
     */
    public QuizPanel(StudentManager sm, Student s, int courseID, Lesson lesson) {
        initComponents();
        setPreferredSize(new java.awt.Dimension(900,700));
        questionsPanel.setLayout(new javax.swing.BoxLayout(questionsPanel, javax.swing.BoxLayout.Y_AXIS));
        scrollPaneQuestions.setViewportView(questionsPanel);
        this.sm = sm;
        this.s = s;
        this.courseID = courseID;
        this.lesson = lesson;
        
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window instanceof javax.swing.JFrame frame) {
            previousSize = frame.getSize();
        }
        
        
        lessonTitleLabel.setText(lesson.getTitle()); //dynamic title generation
        loadQuestion();
        
        if (!sm.canAttemptQuiz(lesson.getLessonId())) {
            submitButton.setEnabled(false);
            submitButton.setText("Maximum attempts reached !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lessonTitleLabel = new javax.swing.JLabel();
        scrollPaneQuestions = new javax.swing.JScrollPane();
        questionsPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        lessonTitleLabel.setFont(new java.awt.Font("Book Antiqua", 2, 28)); // NOI18N
        lessonTitleLabel.setText("             Quiz");

        scrollPaneQuestions.setViewportView(questionsPanel);

        javax.swing.GroupLayout questionsPanelLayout = new javax.swing.GroupLayout(questionsPanel);
        questionsPanel.setLayout(questionsPanelLayout);
        questionsPanelLayout.setHorizontalGroup(
            questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        questionsPanelLayout.setVerticalGroup(
            questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        scrollPaneQuestions.setViewportView(questionsPanel);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lessonTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneQuestions)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lessonTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        Quiz quiz = lesson.getQuiz();
        ArrayList<Integer> submittedAnswers = new ArrayList<>();
        
        for (int i = 0 ; i < optionGroups.size() ; i++) {
            ButtonGroup group = optionGroups.get(i);
            ButtonModel selected = group.getSelection();
            
            if (selected == null) {
                JOptionPane.showMessageDialog(this, "Please answer all questions", "Unanswered Questions" ,JOptionPane.WARNING_MESSAGE);
                return;
            }
            submittedAnswers.add(Integer.parseInt(selected.getActionCommand()));
        }
        
        QuizAttempt attempt;
        try {
            attempt = sm.saveAttempt(courseID, lesson.getLessonId(), submittedAnswers);
        }
        catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Quiz Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int total = attempt.getTotalQuestions();
        int score = attempt.getScore();
        boolean passed = attempt.isPassed();
        String status;
        
        if (passed == true) {
            status = "PASSED";
        }
        else {
            status = "FAILED";
        }
        
        JOptionPane.showMessageDialog(this, "Your score : " + score + "/" + total + "\n" + "Status : " + status);
        
        showFeedback(quiz, submittedAnswers);
        
        for (ButtonGroup group : optionGroups) {
            var buttons = group.getElements();
            while (buttons.hasMoreElements()) {
                JRadioButton b = (JRadioButton) buttons.nextElement();
                b.setEnabled(false);
            }
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        
        if (window instanceof javax.swing.JFrame frame) {
            if (previousSize != null) {
                frame.setSize(previousSize);
                frame.setPreferredSize(previousSize);
            }
            
            frame.getContentPane().removeAll();
            try {
                frame.setContentPane(new lab7.frontend.MarkLessons(courseID, sm, s));
            } catch (IOException ex) {
                Logger.getLogger(QuizPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            frame.revalidate();
            frame.repaint();
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void loadQuestion() {
        Quiz quiz = this.lesson.getQuiz();
        if (quiz == null || quiz.getQuestions().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No quiz is created for this lesson", "Quiz not available", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        questionsPanel.removeAll();
        questionsPanel.setLayout(new BoxLayout(questionsPanel, BoxLayout.Y_AXIS));
        
        for (int i = 0 ; i < quiz.getQuestions().size() ; i++) {
            Question q = quiz.getQuestions().get(i);
            
            JLabel questionTextLabel = new JLabel((i + 1) + ". " + q.getQuestion());
            questionTextLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            questionsPanel.add(questionTextLabel);
            questionLabels.add(questionTextLabel);
            
            ButtonGroup group = new ButtonGroup();
            optionGroups.add(group);
            
            for (int j = 0 ; j < q.getOptions().size() ; j++) {
                JRadioButton option = new JRadioButton(q.getOptions().get(j));
                option.setActionCommand(String.valueOf(j));
                group.add(option);
                questionsPanel.add(option);
            }
            
            JLabel feedback = new JLabel("");
            feedback.setVisible(false);
            feedbackLabels.add(feedback);
            questionsPanel.add(feedback);
            
            questionsPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        }
        
        questionsPanel.revalidate();
        questionsPanel.repaint();
    }
    
    private void showFeedback(Quiz quiz, ArrayList<Integer> answers) {
        for (int i = 0 ; i < quiz.getQuestions().size() ; i++) {
            Question q = quiz.getQuestions().get(i);
            
            int correctAnswer = q.getCorrectAns();
            int submittedAnswer = answers.get(i);
            
            JLabel feedback = feedbackLabels.get(i);
            feedback.setVisible(true);
            
            if (submittedAnswer == correctAnswer) {
                feedback.setText("Correct !");
                feedback.setForeground(new Color(0, 128, 0));
            }
            else {
                feedback.setText("Wrong - Correct Answer : " + q.getOptions().get(correctAnswer));
                feedback.setForeground(Color.RED);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel lessonTitleLabel;
    private javax.swing.JPanel questionsPanel;
    private javax.swing.JScrollPane scrollPaneQuestions;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
